### PR TITLE
Upgrade website to Docusaurus

### PR DESCRIPTION
**Pull request by Soap2G**
Upgrading the `vre-hub` webpage to use the [Docusaurus](https://docusaurus.io/) framework.

Test instance: https://soap2g.github.io/vre-hub/

### CODE REVIEW

**Comment by garciagenrique** [comment]
Hello @Soap2G, this looks amazing !
How difficult would be to add some tabs on the upper side or some index on the right with the main services of the VRE (the same ones that are numbered in the middle of the main page: AAI, RUCIO, REANA, JHUB ? )
Thanks !

**Comment by Soap2G** [comment]
> Hello @Soap2G, this looks amazing ! How difficult would be to add some tabs on the upper side or some index on the right with the main services of the VRE (the same ones that are numbered in the middle of the main page: AAI, RUCIO, REANA, JHUB ? ) Thanks !

Hi @garciagenrique thanks a lot for the suggestion. Done.

**Review by garciagenrique — CHANGES_REQUESTED** [review]
Could please remove the blog entries ? maybe not the blog section (do you thing we would ever use it ?), but at least the example entires :)
https://soap2g.github.io/vre-hub/blog/

**Review by garciagenrique — APPROVED** [review]
🫶🫶

**Pull request merged**
